# Question 1

In [1]:
import numpy as np
np.arange(2,53,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

# Question 2

In [2]:
import numpy as np
list_1=[]
list_2=[]
for i in range(0,5):
    num1=int(input())
    list_1.append(num1)
for j in range(0,5):
    num2=int(input())
    list_2.append(num2)
st=np.array(list_1)
nd=np.array(list_2)
rd=np.concatenate((st,nd))
print(rd)
print(np.sort(nd))
print(np.sort(st))

1
2
3
4
5
6
7
8
9
0
[1 2 3 4 5 6 7 8 9 0]
[0 6 7 8 9]
[1 2 3 4 5]


# Question 3

In [6]:
import numpy as np
x = np.array([[1, 2, 3, 4],[5,6,7,8]])
print(x.shape)
print(x.size)

(2, 4)
8


# Question 4

In [7]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_2d = np.reshape(arr, (2, 5))
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [8]:
x1 = np.array([1, 2, 3, 4, 5])
x1_new = x1[:, np.newaxis]  
print(x1_new)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [9]:
x = np.array([1, 2])
y = np.expand_dims(x, axis=0)
y

array([[1, 2]])

# Question 5

In [11]:
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Horizontal Append:', np.hstack((f, g)))
print('Vertical Append:', np.vstack((f, g)))

Horizontal Append: [1 2 3 4 5 6]
Vertical Append: [[1 2 3]
 [4 5 6]]


# Question 6

In [14]:


import numpy as np 

  

ini_array = np.array([10, 20, 5, 

                      10, 8, 20, 

                      8, 9]) 

  
# Get a tuple of unique values  
# and their frequency in 
# numpy array 

unique, frequency = np.unique(ini_array,  

                              return_counts = True) 
# print unique values array 

print("Unique Values:",  

      unique) 

  
# print frequency array 

print("Frequency Values:",frequency)

Unique Values: [ 5  8  9 10 20]
Frequency Values: [1 2 1 2 2]
